SME.Pedagogico.Gestao.Data/Functionalities/HttpHelper.cs, SME.Pedagogico.Gestao.Data/Functionalities/NumberExtensions.cs, SME.Pedagogico.Gestao.Data/Functionalities/StringExtensions.cs, SME.Pedagogico.Gestao.Data/Integracao/CargosAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/BuscaTurmasAtribuidasDTO.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/CargosDTO.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/TurmasDTO.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/ProfessoresAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/TurmasAPI.cs, SME.Pedagogico.Gestao.Data/SME.Pedagogico.Gestao.Data.csproj
- Implementação do método HttpHelper
- Chamada dos métodos de Cargos
- Chamada dos métodos de Turma
- Chamada dos métodos de Professores
=> Desenvolvimento das chamadas da API Integração.

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.Data/DTO/PollReportItemDTO.cs, SME.Pedagogico.Gestao.Data/Enums/PollTypeEnum.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PollSelectYesNo.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathGridHeader.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathNumbersChart.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/routes/AuthenticatedDashboardProfileRoute.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Filters.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/User.js
Correção relatório consolidado ordem 5 3º ano
=> Correção relatório consolidado ordem 5 3º ano

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs
[Ajuste] - ajuste na tarefa 3287
=> [Ajuste] - ajuste na tarefa 3287

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs
[Ajuste] - ajuste na tarefa 3287 dev
=> [Ajuste] - ajuste na tarefa 3287 dev

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PollSelectYesNo.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathNumbersChart.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/routes/AuthenticatedDashboardProfileRoute.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Filters.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/User.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/PollReport.js, SME.Pedagogico.Gestao.WebApp/Controllers/CargoController.cs
Correcao 3106 transicao de relatorio portugues/matematica consolidado
=> Correcao 3106 transicao de relatorio portugues/matematica consolidado

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js
[Ajuste] - Mudanca na data da aplicaçao da sondagem do dia 16-09 par  02-09
=> [Ajuste] - Mudanca na data da aplicaçao da sondagem

SME.Pedagogico.Gestao.Data/Business/Profile.cs, SME.Pedagogico.Gestao.WebApp/Controllers/AuthController.cs
[Ajuste] - ajuste no projeto para que os professores do cargo 3310 - PROF.1.GRAU NIVEL II possam acessar a Sondagem
=> [Ajuste] - ajuste no projeto para que os professores do cargo 3310

SME.Pedagogico.Gestao.WebApp/Controllers/AuthController.cs
[Ajuste] - Ajuste feito para que o professor sem turmas atribuídas não consiga logar no sistema
=> [Ajuste] - Ajuste professor sem turmas atribuídas

SME.Pedagogico.Gestao.Data/Business/Authentication.cs, SME.Pedagogico.Gestao.Data/Business/Profile.cs, SME.Pedagogico.Gestao.Data/DTO/BuscaPerfilServidor.cs, SME.Pedagogico.Gestao.Data/DTO/RoleAuthenticationDto.cs, SME.Pedagogico.Gestao.Data/Integracao/PerfilSgpAPI.cs, SME.Pedagogico.Gestao.Models/Auth/UserRoleModel.cs, SME.Pedagogico.Gestao.Models/Authentication/UserRole.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/package-lock.json, SME.Pedagogico.Gestao.WebApp/ClientApp/public/index.html, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/User.js, SME.Pedagogico.Gestao.WebApp/Controllers/AuthController.cs, SME.Pedagogico.Gestao.WebApp/Controllers/CargoController.cs
Correção titulo navegador
AB#15293 AB#15649
=> Correção login quando perfi selecionado não pode selecionar sondagem

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemAutoral.js
Correção de ano escolar
AB#23434 AB#23435
=> Correção de ano escolar

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js
Correção de pergunta ao mudar de turma
AB#23442
=> Correção de pergunta ao mudar de turma

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/DTO/Portugues/AlunoSondagemPortuguesDTO.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesController.cs
Sondagem de Portugues (4º ao 9º ano) (Capacidade de Leitura)
AB#20900
=> Sondagem de Portugues (4º ao 9º ano) (Capacidade de Leitura)

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/DTO/Matematica/FiltrarListagemDto.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/seletorDeordem.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Consumir endpoint de ordens selecionadas
AB#20900
=> Consumir endpoint de ordens selecionadas

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/select.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/radioButton.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/seletorDeordem.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesController.cs
=> Correções e ajustes radio button

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/seletorDeordem.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Limpar seleção, correções e ajustes de layout
AB#20900  AB#23886
=> Limpar seleção, correções e ajustes de layout

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/aluno.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/select.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/Filters.js
[AB#23893](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23893) [AB#24181](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24181)
=> 23893 - Correção tooltip dropbox

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/seletorDeordem.js
[AB#24385](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24385) [AB#23933](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23933)
=> 24385 - colocar icone de check quando tiver registro salvo

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js
[AB#24448](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24448) [AB#23925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23925)
=> 24448 - Ajuste desabilitar seta na primeira ordenação e na última

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/DTO/RespostaDto.cs, SME.Pedagogico.Gestao.Models/Autoral/Resposta.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/checkbox.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/mensagemConfirmacaoAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/radioButton.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/select.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemConfirmacao.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Língua Portuguesa (Digitação) - Leitura em voz alta
[AB#22032](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22032)
=> Língua Portuguesa (Digitação) - Leitura em voz alta

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/checkbox.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Língua Portuguesa (Digitação) - Produção de texto escrito
[AB#22748](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22748)
=> Língua Portuguesa (Digitação) - Produção de texto escrito

SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Correção em edicao
[AB#22748](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22748)
=> Correção em edicao

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Contexts/SMEManagementContextData.cs, SME.Pedagogico.Gestao.Data/DTO/Portugues/AlunoSondagemPortuguesDTO2.cs, SME.Pedagogico.Gestao.Models/Autoral/Sondagem.cs, SME.Pedagogico.Gestao.Models/Autoral/SondagemAluno.cs, SME.Pedagogico.Gestao.Models/Autoral/SondagemAlunoRespostas.cs, SME.Pedagogico.Gestao.Models/Autoral/SondagemAutoral.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesController.cs
[AB#23949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23949)  
1. Alteração nos método de salvar de português 
2. Alteração no método de listar de português 
3. Alteração na modelagem do banco para a expansão da sondagem
=> AB#23949  Estratégia para relatório dos estudantes 

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemConfirmacao.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemAutoral.js
Salvamento de Matemática e Mensagens de confirmação
[AB#23949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23949) [AB#24555](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24555)
=> Salvamento de Matemática e Mensagens de confirmação

SME.Pedagogico.Gestao.WebApp/ClientApp/package-lock.json, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js
Correção perguntaId FrontEnd
[AB#24671](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24671)
=> Correção perguntaId FrontEnd

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/mensagemLimparSelecao.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesController.cs
Exclusão de Sondagem Limpar seleções
[AB#23948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23948)
=> Exclusão de Sondagem Limpar seleções

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/mensagemLimparSelecao.js
Correção mensagem limpar seleção
[AB#24786](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24786)
=> Correção mensagem limpar seleção

SME.Pedagogico.Gestao.Data/DTO/Matematica/FiltrarListagemMatematicaDTO.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/radioButton.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemAutoral.js
Correção listagem ao salvar
[AB#25007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25007)
=> Correção listagem ao Salvar

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemConfirmacao.js
[AB#25035](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25035)
=> Correção na exibição de mensagem ao trocar de matéria

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/radioButton.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Correção troca de grupos
[AB#25040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25040)
=> Correção troca de grupos

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/mensagemConfirmacaoAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/mensagemLimparSelecao.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemConfirmacao.js
[AB#25041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25041)
=> Ajuste nas mensagens de feedback das ações de salvar e Limpar seleções

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/seletorDeordem.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
Correção sequencia ordem salva
[AB#25046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25046)
=> Correção sequencia ordem salva

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#25131](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25131)
=> 25131 - Ajustes filtros

SME.Pedagogico.Gestao.Data/Functionalities/HttpHelper.cs, SME.Pedagogico.Gestao.Data/Integracao/AlunosAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/FiltroTotalAlunosAtivos.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsAPI.cs
Desenvolvimento da API de Alunos
[AB#24567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24567)
=> Api Alunos

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaConsolidado.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaConsolidado.js
[AB#25141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25141)
=> 25141 - Criação do componente

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportBreadcrumb.js
[AB#25138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25138)
=> 25138 - Ajustes controle de layout

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemInformacao.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/MensagemConfirmacaoImprimir.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/PollReport.js
alterando botão imprimir e preparando para chamada de endpoint [AB#25197](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25197)
=> alterando botão imprimir e preparando para chamada de endpoint

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js
[AB#25144](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25144)
=> 25144 - Consumo de endpoint

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js
[AB#25555](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25555)
=> 25555 - Ajuste na largura das colunas da tabela

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Functionalities/HttpHelper.cs, SME.Pedagogico.Gestao.Data/Integracao/AlunosAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsAPI.cs
[AB#25903](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25903)
=> Consumindo endpoint de alunos ativos por turma e periodo

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js
Correção: Não está salvando as Sondagens antigas
[AB#25815](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25815)
=> Correção: Não está salvando as Sondagens antigas

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathGridHeader.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js
[AB#25901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25901)
=> 25901 - Alteração da coluna "Alunos" para "Nome do estudante"

SME.Pedagogico.Gestao.Data/Business/Profile.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsNovoSGP.cs, SME.Pedagogico.Gestao.Data/Integracao/NovoSGPAPI.cs
Ajuste na rotina que busca as abrangência do usuário, considerando somente histórico para usuários com o perfil de professor.
=> Bug: 25478

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs
Correção produção de texto e leitura em voz alta
=> Correção Produção de texto e leitura em voz alta

SME.Pedagogico.Gestao.Data/Business/Authentication.cs
Ajuste na funcionalidade que obtém o usuário corrente incluindo um tratamento quando o login possui espaços.
=> Bug: 25950

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/Mock.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js
[AB#26062](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26062)
=> 26062 - Componente Capacidade de leitura por Turma

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/GraficoPerguntaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/GraficoPorTurmaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/Mock.js
[AB#24566](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24566)
=> 24566 - Gráfico capacidade Leitura

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaProducaoTexto/MockProducaoTexto.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaProducaoTexto/RelatorioPorTurmaProducaoTexto.js
[AB#26090](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26090)
=> 26090 - Componente de Producao de texto

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaProducaoTexto/GraficoPorTurmaProducaoTexto.js
[AB#26091](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26091)
=> 26091 - Grafico producao de texto por turma

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematicaPorTurma/GraficoMatematicaPorTurma.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaPorTurma/RelatorioMatematicaPorTurma.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js
[AB#25984](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25984)
=> 25984 - Consumir endpoints de construção do relatório e gráfico

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js
Correção botão inativo
[AB#26245](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26245)
=> Correção botão inativo

SME.Pedagogico.Gestao.Aplicacao/CasosDeUso/Relatorios/RelatorioImpressaoUseCase.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/TipoRelatorio.cs, SME.Pedagogico.Gestao.Infra/Dtos/Relatorios/RelatorioImpressaoFiltroDto.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioController.cs
[AB#24780](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24780)
=> Ajustes na API para chamar relatório de Português AB#26156

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaPorTurma/RelatorioMatematicaPorTurma.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaPorTurma/RelatorioMatematicaPorTurma.js
[AB#26447](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26447) [AB#26450](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26450)
=> 26447 - Ajustes textos extrapolando o tamanho da célula

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
Correção Ordenação preenchimento
[AB#26483](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26483)
=> Correção ordenação preenchimento

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs, SME.Pedagogico.Gestao.Data/Enums/AlunoInativoEnum.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/RetornoQueryDTO/AlunosNaTurmaDTO.cs
Ajuste inativo e ordem perguntas
[AB#26446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26446)
=> Ajuste inativo

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
Ajuste nome aluno relatório matemática autoral
=> Ajuste nome aluno relatorio matematica autoral

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioPorTurma/AlunoPorTurmaCapacidadeLeituraDTO.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/GraficoPerguntaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/GraficoPorTurmaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js
[AB#26064](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26064)
=> 26064 - Consumo de endpoints capacidade de leitura

SME.Pedagogico.Gestao.Infra/Dtos/Relatorios/RelatorioImpressaoFiltroDto.cs
[AB#26393](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26393)
=> Adição de GrupoId no FiltroDto

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs, SME.Pedagogico.Gestao.Data/DTO/Portugues/Relatorio/RelatorioAutoralLeituraProducaoDto.cs
Graficos consolidados leitura em voz alta e produção de texto
=> Graficos consolidados leitura em voz alta e produção de texto

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs
Gráficos consolidados leitura em voz alta e produção de texto quando não possui informação
=> Graficos consolidados leitura em voz alta e produção de texto quando não possui informação

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/PollReport.js
[AB#26624](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26624)  [AB#26549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26549)
=> 26624 - Correção: tratamento de dados para diferentes filtros

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/Grafico/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoConsolidadoMatematica/GraficoConsolidadoMatematica.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematica/GraficoMatematica.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematicaPorTurma/GraficoMatematicaPorTurma.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js
[AB#26477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26477)
=> 26477 - Gráficos de matemática

SME.Pedagogico.Gestao.Aplicacao/CasosDeUso/Relatorios/RelatorioImpressaoUseCase.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/TipoRelatorio.cs
[AB#26760](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26760) [AB#26742](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26742)
=> Correção dos relatórios de matemática aditivo e multip impressos como números

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathChart.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathChartClassroom.js
[AB#26659](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26659)
=> 26659 - Inserir dados sem preenchimentos nos gráficos campo aditivo e multiplicativo

SME.Pedagogico.Gestao.Data/Business/SondagemMatematicaTurma.cs, SME.Pedagogico.Gestao.Data/DTO/MathChartDataModel.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioGraficoNumerosDTO.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#26642](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26642) [AB#26963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26963)
=> 26642 - Matemática números sem preenchimento

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
Língua Portuguesa consolidado abaixo do 4º Ano
[AB#26641](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26641)
=> Lingua Portuguesa Consolidado

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Constantes.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/package-lock.json, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
Portugues por turma anterior ao 4 ano
[AB#26638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26638)
=> Portugues por turma anterior ao 4 ano

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/Grafico/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoConsolidadoCapacidadeLeitura/GraficoCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematica/GraficoMatematica.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaCapacidadeLeitura/GraficoPerguntaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaLeituraVozAlta/GraficoPorTurmaLeituraVozAlta.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoPorTurmaProducaoTexto/GraficoPorTurmaProducaoTexto.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/utils/utils.js
[AB#27151](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27151) [AB#27152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27152)
=> 27152 - Ajuste quebra tooltip

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.Data/DTO/PollReportItemDTO.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
Consolidado matematica consolidado multiplicativo
[AB#26646](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26646)
=> Consolidado matematica consolidado multiplicativo

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathGrid.js
[AB#26645](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26645)
=> 26645 - Adicionar alunos sem preenchimento no relatório matemática campo aditivo

SME.Pedagogico.Gestao.Data/Business/AlunosBusiness.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportMathChartClassroom.js, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#27333](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27333)
=> 27333 - Sem preenchimento portugues consoldado

SME.Pedagogico.Gestao.Aplicacao/CasosDeUso/Relatorios/RelatorioImpressaoUseCase.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/GrupoEnum.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/TipoRelatorio.cs
[AB#25978](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25978)
=> Endpoint pt consolidado

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs, SME.Pedagogico.Gestao.Data/SME.Pedagogico.Gestao.Data.csproj
[AB#28104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28104) [AB#28105](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28105)
=> 28104 - Correção ordenação e retirar porcentagem total

SME.Pedagogico.Gestao.WebApp/ClientApp/src/Enums.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
Reverts prefeiturasp/SME-Pedagogico-Gestao#266
=> Revert "feature/29285"

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
[AB#30868](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30868) [AB#30890](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30890)
=> 30868 - Ajuste busca de turmas

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/Filters.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/utils/verificarDisciplina.js
Ajuste no erro de tela branca ao selecionar o componente de Matemática de turma de 7ª série.
Inclusão de veirficações de variáveis nulas e atribuição de valores no redux.
=> Bug: 32549

SME.Pedagogico.Gestao.WebApp/ClientApp/package-lock.json, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js
=> Fix:43270 rel

SME.Pedagogico.Gestao.WebApp/ClientApp/package-lock.json, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js
=> 43270 - ajuste para não buscar perguntas com ordem -1

SME.Pedagogico.Gestao.WebApp/Middlewares/FiltroExcecoesAttribute.cs
Incluindo a mensagem da exceção para identificação do erro.
=> Big: 50632

SME.Pedagogico.Gestao.WebApp/Middlewares/FiltroExcecoesAttribute.cs
=> Bug: 50632

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioAutoral/RelatorioPortuguesAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioConsolidadeCapacidadeLeitura/RelatorioConsolidadoCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaConsolidado.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaPorTurma/RelatorioMatematicaPorTurma.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaLeituraVozAlta/RelatorioPorTurmaLeituraVozAlta.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaProducaoTexto/RelatorioPorTurmaProducaoTexto.js
matemática autoral (7º ao 9º) e língua portuguesa leitura em voz alta, produção de texto e capacidade de leitura (4º ao 9º
=> feature/52772 - Ampliação 2020 - Aplicar cores nas telas

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioAutoral/RelatorioPortuguesAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioConsolidadeCapacidadeLeitura/RelatorioConsolidadoCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaConsolidado.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaPorTurma/RelatorioMatematicaPorTurma.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaLeituraVozAlta/RelatorioPorTurmaLeituraVozAlta.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaProducaoTexto/RelatorioPorTurmaProducaoTexto.js
[AB#27446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27446)
=> story/27446  - Ampliação 2020 - Aplicar cores nas telas

SME.Pedagogico.Gestao.WebApp/Middlewares/FiltroExcecoesAttribute.cs
Implementação para descobrir causa do bug ao logar.
=> Bug: 51445

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
Ajuste na listagem de turmas para considerar históricas e não históricas.
=> Bug: 56478

SME.Pedagogico.Gestao.Aplicacao/Queries/Relatorios/Comum/ObterRelatorioSincrono/ObterRelatorioSincronoQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
Ajustes na rotina de relatório para obter as informações de português em relação a quantidade, item sem preenchimento e problema de tela branca.
=> Bug: 57193

SME.Pedagogico.Gestao.Data/Contexts/SMEManagementContextData.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/TurmasAPI.cs
[AB#58915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58915)
[AB#58877](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58877)
=> Correção de transient failure no context

SME.Pedagogico.Gestao.Data/DTO/PerguntaDto.cs, SME.Pedagogico.Gestao.Models/Autoral/ComponenteCurricular.cs, SME.Pedagogico.Gestao.Models/Autoral/Pergunta.cs, SME.Pedagogico.Gestao.Models/Autoral/PerguntaAnoEscolar.cs, SME.Pedagogico.Gestao.Models/Autoral/PerguntaResposta.cs, SME.Pedagogico.Gestao.Models/Autoral/Resposta.cs, scripts/V9__INCLUIR_CAMPO_PERGUNTA_PAI_ID_TABELA_PERGUNTA.sql, scripts/V9__INCLUIR_CAMPO_PERGUNTA_PAI_ID_TABELA_PERGUNTA.sql.bak
[AB#58677](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58677)
=> Modelagem DB

SME.Pedagogico.Gestao.Models/Autoral/PerguntaAnoEscolar.cs, scripts/V7_INCLUIR_CAMPO_DATAVIGENCIA_PERGUNTA_ANO_ESCOLAR.sql
[AB#58702](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58702)
=> 58702 - Modelagem DB (data vigência para PeriodoAnoEscolar)

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Models/Autoral/PerguntaAnoEscolar.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
[AB#58704](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58704)
=> 58704 - Alterar endpoint de perguntas

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/DTO/Matematica/AlunoSondagemMatematicaDto.cs, SME.Pedagogico.Gestao.Data/DTO/Matematica/FiltrarListagemMatematicaDTO.cs, SME.Pedagogico.Gestao.Models/Autoral/Sondagem.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs, scripts/V10__INCLUIR_BIMESTRE_SONDAGEM.sql
[AB#59007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59007)
=> Alterar Endoint Períodos

SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
[AB#59007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59007)
=> alteração nome da rota

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/DTO/Matematica/FiltrarListagemMatematicaDTO.cs, SME.Pedagogico.Gestao.Models/Autoral/PerguntaAnoEscolar.cs, SME.Pedagogico.Gestao.Models/Autoral/Sondagem.cs, SME.Pedagogico.Gestao.Models/Autoral/SondagemAlunoRespostas.cs, scripts/V10__INCLUIR_BIMESTRE_SONDAGEM.sql
[AB#59070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59070)
=> Alterar Endpoint obter resposta

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/MensagemConfirmacao.js
[AB#58965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58965)
=> 58965 - ajuste na troca de componentes na sondagem (modal não saia da tela ao fazer alguma ação)

scripts/V12__INSERT_CARGA_PERGUNTAS_MATEMATICA_2022.sql, scripts/V8_UPDATE_ENCERRAR_VIGENCIA_QUESTOES_ANTERIORES.sql
[AB#58703](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58703)
=> 58703 - script para carga de perguntas matemática 2022

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#59070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59070)
=> Correção para editar registro

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.Data/Integracao/Endpoints/EndpointsAPI.cs, SME.Pedagogico.Gestao.Data/Integracao/TurmasAPI.cs
Ajuste na chamada do endpoint da API/EOL para obter os alunos e não ocasionar repetição.
=> Bug: 59575

scripts/V13__INCLUIR_GRUPO_PERGUNTA_ANO_ESCOLAR_PERGUNTA_ID.sql, scripts/V14__INCLUIR_CARGA_1_AO_3_PERGUNTAS_MATEMATICA_2022.sql
[AB#58678](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58678)
=> script para carga de perguntas do 1 ao 3 ano

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs
Story/58356 --> DEV  - Remoção de ano letivo conforme bug 59575
=> Story/58356 --> DEV  - Remoção de ano letivo conforme bug 59575

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
Correção da busca de perguntas autorais (pós alteração de alfabetização)
=> Correção da busca de perguntas autorais (pós alteração de alfabetização)

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#60200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60200)
[AB#60123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60123)
=> ajustado para retornar uma lista vazia quando não encontrar as respostas

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#59793](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59793)
=> fix/59793 - ajuste para ordenação de alunos sondagem (numero da chamada 0)

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemAutoral.js, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
[AB#60317](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60317)
[AB#60123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60123)
=> Correção Query de Consulta de Perguntas

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
Ajuste na listagem de turmas fazendo a distinção dessas em caso de repetição.
=> Bug: 60111

SME.Pedagogico.Gestao.WebApp/ClientApp/src/App.css, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemAutoral.js
[AB#60350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60350)
[AB#60123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60123)
=> Correção de erro ao exibir as repostas

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#60253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60253)
=> Ajustando a persistência

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioMatematicaConsolidadoCACM.js
[AB#60460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60460)
=> 60460 - ajuste na exibição da porcentagem 

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#60465](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60465)
=> 60465 correção de perguntas duplicadas no relatório (tela)

SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#60476](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60476)
[AB#60553](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60553)
=> Ordenação de perguntas e respostas

SME.Pedagogico.Gestao.Models/Autoral/Pergunta.cs, SME.Pedagogico.Gestao.Models/Autoral/PerguntaResposta.cs, scripts/V15__UPDATE_ORDENACAO_PERGUNTA_RESPOSTA.sql
[AB#60343](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60343)
[AB#60589](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60589)
=> Alterado ordem da da respostas

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
[AB#60467](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60467)
=> #correção bug

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/DTO/Matematica/Relatorio/filtrosRelatorioDTO.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioMatematicaPorTurmaProficienciaDTO.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioPorTurma/CabecalhoRelatorioProficienciaDTO.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioPorTurma/PerguntaPrincipalTurmaProficienciaDTO.cs, SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#60022](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60022)
[AB#60038](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60038)
=> Inclusão do cabeçalho do relatório de tela por turma proficiência

SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
=> removido where duplicado

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#60506](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60506)
=> Correção consulta relatório tela matematica

SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs
[AB#61216](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61216)
=> Ordenação dos alunos na digitação CA e CM.

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs
[AB#61335](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61335)
=> Relatório por turma presentando nome social quando houver

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterVerificarPerfisUesTipos/ObterVerificarPerfisUesTiposQueryHandler.cs, SME.Pedagogico.Gestao.WebApp/Configuracoes/RegistraClientesHttp.cs
[AB#61563](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61563)
=> Sondagem - Adicionado ChaveIntegracaoSgpApi

scripts/V18__MIGRACAO_DE_DADOS_2022_CM.sql
[AB#62351](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62351)
[AB#61864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61864)
=> Migração da tabela MathPoolCMs para sondagem.

scripts/V17__MIGRADOR_DE_DADOS_2022_NUMEROS.sql
[AB#62350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62350)
[AB#61862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61862)
=> Script de migração MathPoolNumbers para sondagem 2022

scripts/V16__MIGRADOR_DE_DADOS_2022_CA.sql
[AB#61770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61770)
[AB#61863](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61863)
=> Script de migração MathPoolCAs para sondagem

scripts/V16__MIGRADOR_DE_DADOS_2022_CA.sql, scripts/V18__MIGRACAO_DE_DADOS_2022_CM.sql
[AB#62351](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62351)
[AB#61864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61864)
[AB#62655](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62655)
[AB#62656](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62656)
=> Correção no script de CM

scripts/V17__MIGRADOR_DE_DADOS_2022_NUMEROS.sql, scripts/V18__MIGRACAO_DE_DADOS_2022_CM.sql, scripts/V19__UPDATE_GRUPO_CA_PERGUNTAANOESCOLAR.sql, scripts/V20__MIGRADOR_DE_DADOS_2022_3ANO_CA.sql
[AB#63246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63246)
[AB#63287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63287)
=> Correção dos script de migração

scripts/V17__MIGRADOR_DE_DADOS_2022_NUMEROS.sql
[AB#62350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62350)
[AB#61862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61862)
[AB#62655](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62655)
[AB#62656](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62656)
=> Correção script Número

scripts/V21__DELETE_PERGUNTAS_PRIMEIRA_CARGA_MATEMATICA_4_9_ANO_2022.sql, scripts/V22__NOVA_CARGA_PERGUNTAS_MATEMATICA_4_AO_9_ANO_2022.sql
[AB#63257](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63257)
=> Feature/63257 - delete de perguntas alteradas e insert de perguntas novas - matemática

scripts/V21__DELETE_PERGUNTAS_PRIMEIRA_CARGA_MATEMATICA_4_9_ANO_2022.sql, scripts/V22__NOVA_CARGA_PERGUNTAS_MATEMATICA_4_AO_9_ANO_2022.sql
[AB#63256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63256)
[AB#63569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63569)
=> Story/63256 - alteração nas perguntas do 4 ao 9

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#64004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64004)
=> fix/64004 - ajuste para alteração de respostas em tela 

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/NovaSondagemMatematicaAutoral/novoAluno.js
[AB#64193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64193)
=> Correção a busca pela resposta autoral

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Infra/SituacaoMatriculaAluno.cs
[AB#64010](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64010)
=> Fix/64010 - ajustes para exibição correta de alunos inativos 

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
[AB#64227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64227)
=> fix/64227 - ajustes para tratar turmas duplicadas sondagem ano atual e anterior

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematica/GraficoMatematica.js
[AB#64105](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64105)
=> Correção na cor do grafico

scripts/V23__UPDATE_QUESTAO_7ANO_PERGUNTA2_ALTERNATIVA3_MATEMATICA_2022.sql
[AB#64310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64310)
=> 64310 - ajuste de alternativa no 7 ano da nova carga de perguntas 2022.

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#64010](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64010)
=> fix/64010 - ajuste de validação ao salvar/alterar resposta do aluno

scripts/V24__UPDATE_PERGUNTAS_E_ALTERNATIVA_QUESTAO_5_7_ANO_MATEMATICA_2022.sql
[AB#64355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64355)
=> fix/64355 - inclusão do número da questão e ajuste na alternativa da questão 5 do 7 ano - matemática 2022

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Integracao/TurmasAPI.cs
[AB#64010](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64010)
=> Fix/64010 - ajuste de validação na listagem de alunos inativos

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#64927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64927)
=> Fix/64927 - ajuste de ordenação de respostas na tela de relatório (português - proficiência escrita)

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterVerificarPerfisDoUsuarioLogin/ObterVerificarPerfisDoUsuarioLoginQueryHandler.cs, SME.Pedagogico.Gestao.Infra/Perfil.cs
[AB#65433](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65433)
=> Correção do bug 65433

scripts_diversos/64226 - Relatório das Escolas sem Sondagem/Consulta Matematica.sql, scripts_diversos/64226 - Relatório das Escolas sem Sondagem/Consulta Portugues.sql, scripts_diversos/64226 - Relatório das Escolas sem Sondagem/Exportação Turmas SGP.sql
[AB#64226](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64226)
=> 64226 Scripts Exportação Escolas sem Sondagem

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#66171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66171)
=> Fix/66171 - ajuste na contagem do relatório 

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/DTO/SondagemAutoralDTO.cs
[AB#67337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67337) [AB#67214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67214)
=> Fix/67214 - ajuste de query na consulta de obtersondagem

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/DTO/SondagemAutoralDTO.cs
[AB#67214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67214)
=> Fix/67214 (obtersondagemautoral + salvar) -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#67208](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67208)
=> Correção do bug 67208

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Interceptors/QueryInterceptors.cs, SME.Pedagogico.Gestao.Infra/SME.Pedagogico.Gestao.Infra.csproj, SME.Pedagogico.Gestao.Infra/Telemetria/IServicoTelemetria.cs, SME.Pedagogico.Gestao.Infra/Telemetria/ServicoTelemetria.cs, SME.Pedagogico.Gestao.Infra/Utilitarios/TelemetriaOptions.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs, SME.Pedagogico.Gestao.WebApp/SME.Pedagogico.Gestao.WebApp.csproj, SME.Pedagogico.Gestao.WebApp/Startup.cs
[AB#66352](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66352)
[AB#67490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67490)
=> Fix/66352 to R2

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#67467](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67467)
=> Agrupamento de Respostas por Aluno

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Interceptors/QueryInterceptors.cs
[AB#66352](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66352)
[AB#67640](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67640)
=> Logar Etapas do Repositorio Sondagem no Trace do APM

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/NovaSondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js
Sondagem - Está enviando bimestre nulo para o backend
[AB#67730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67730)
[AB#67880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67880)
=> Correção erro de envio bimestre para o back

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/TwoStepsSave.js
[AB#67880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67880)
[AB#67730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67730)
=> Correção na exibição da Mensagem de Erro

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/TwoStepsSave.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
[AB#67924](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67924)
=> Fix/67924 - ajuste na mensagem feedback sondagem autoral (mat e port)

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/NovaSondagem/novaSondagemCACM.js
[AB#67730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67730) [AB#68784](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68784)
=> fix/67730 - ajuste de bimestre null para novas sondagens CA e CM

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/NovaSondagem/novaSondagemCACM.js
[AB#67730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67730)
=> fix/67730 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/TwoStepsSave.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/SondagemPortuguesStore.js
[AB#67924](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67924)
=> fix/67924 -> master

SME.Pedagogico.Gestao.Aplicacao/Commands/SondagemAutoral/ExcluirSondagemMatematica2022ComDivergencias/ExcluirSondagemMatematica2022ComDivergenciasCommandHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/ComponenteCurricularEnum.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
[AB#68638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68638)
[AB#68676](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68676)
=> Fix/68638 to R2

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#68638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68638)
[AB#68676](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68676)
=> Ajustado método que remove respostas não alteradas para não respondidas.

SME.Pedagogico.Gestao.Aplicacao/Commands/SondagemAutoral/ExcluirSondagemMatematica2022ComDivergencias/ExcluirSondagemMatematica2022ComDivergenciasCommandHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/ComponenteCurricularEnum.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs
Ajustado método que remove respostas não alteradas para não respondidas.
[AB#68638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68638)
[AB#68867](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68867)
=> Corrigido problema de duplicidade do sondagem.

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/messaging/TwoStepsSave.js
[AB#69266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69266)
=> Correção do bug 69266

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#66077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66077)
=> fix 66077 - ajuste Erro na consulta de relatórios de LP (Leitura e escrita)

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#66077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66077)
=> master - fix 66077 ajuste Erro na consulta de relatórios de LP (Leitura e escrita)

SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/PollReport.js
Ajuste na exibição de planilha e gráficos na seleção de filtro para português, resgatando as propriedades corretas retornadas pelo back-end.
=> Bug: 67912 master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/funcoes/componentRenderReport.js
[AB#64927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64927)
=> r2 64927 - carregar dados relatório 1,2,3 ano

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/funcoes/componentRenderReport.js
[AB#64927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64927)
=> master 64927 - carregar dados relatório 1,2,3 ano

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#70972](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70972)
=> fix/70972 - ajuste para exibir dados do português consolidado do 3 ano.

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#73628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73628)
=> fix/73628 -> r2

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#75270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75270)
=> Fix/75270 -> r2

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#75270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75270)
=> fix/75270 -> master

scripts/V26__CRIAR_TABELA_PERGUNTAANOESCOLARBIMESTRE.sql
[AB#74988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74988) Criar nova entidade (script)
=> Feature 74988 - Criar nova entidade (script)

scripts/V27__NOVA_CARGA_PERGUNTAS_RESPOSTAS_MATEMATICA_4_BIMESTRE_4_AO_9_ANO_2022.sql
[AB#74989](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74989)
=> Cria carga de dados (scripts)

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs, scripts/V27__NOVA_CARGA_PERGUNTAS_RESPOSTAS_MATEMATICA_4_BIMESTRE_4_AO_9_ANO_2022.sql
[AB#76509](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76509) - Ajustes nos textos de perguntas e respostas
[AB#76524](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76524)
=> Fix/76509 - Ajustes nos textos de perguntas e respostas

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#75936](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75936)
=> 75936 - Ajuste nas consultas de questões por bimestre

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#74956](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74956)
=> 74956 - Ajuste na consulta

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLogin/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLoginQueryHandler.cs, SME.Pedagogico.Gestao.WebApp/Controllers/AuthController.cs
[AB#77487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77487)
=> Professor sem acesso está conseguindo logar

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLogin/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLoginQueryHandler.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Filters.js
[AB#77585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77585)
=> Quando só tem um perfil o sondagem já entra direto não aparece tela de selecionar perfil 

SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#77887](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77887)
=> 77887 - Pergunta do 4 bimestre sendo apresentada em outros bimestre.

SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#78558](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78558)
=> Correção do bug 78558

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#78511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78511)
=> fix/78511 -> r2

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#78521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78521)
=> R2 Limpando dados ao fazer nova pesquisa na tela de relatório

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js
[AB#78519](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78519)
=> Ajuste nas colunas do relatório capacidade de leitura

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#78511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78511)
=> fix/78511 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#78521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78521)
=> Limpando dados ao fazer nova pesquisa na tela de relatório

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.css.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/RelatorioPorTurmaCapacidadeLeitura/RelatorioPorTurmaCapacidadeLeitura.js
[AB#78523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78523)
=> R2 Ajuste relatório consolidado para perfil de professor

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/tabelaAlunos.js
[AB#77418](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77418)
=> R2 Fix/77418 - Adição de loader ao carregar dados do bimentre na aba sondagem - Capacidade de leitura

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js
[AB#78523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78523)
=> fix/78523 -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#79714](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79714)
=> fix/79714 -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#80626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80626)
=> Correção do bloqueio da aba Ordem do Narrar

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#83307](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83307)
=> Obter alunos ativos para o Sondagem.

SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Filters.js
[AB#83253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83253)
=> fix/83253 -> r2

SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Filters.js
[AB#83253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83253)
=> fix/83253 -> master

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#83955](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83955)
=> fix/83955 -> master

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#84253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84253)
=> Fix/84253 -> r2

scripts/V28__NOVA_CARGA_PERGUNTAS_RESPOSTAS_ANO_2023.sql
[AB#84654](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84654)
=> Carga das questões do sondagem

scripts/V25__INDICES_SONDAGEM.sql
This reverts commit e3314866344c4f867c567bdf823dc81a5dd2c4cb.
=> Revert "Índices sendo criados sem validar se já existem"

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs
[AB#85315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85315)
[AB#85351](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85351)
=> Correção da Query de perguntas

SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#85620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85620)
=> Fix/85620 -> r2

SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#85750](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85750)
=> fix/85750 -> master

SME.Pedagogico.Gestao.Data/Business/PeriodoAbertura.cs, SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.Models/Enums/TipoPeriodoEnum.cs, SME.Pedagogico.Gestao.Models/Organization/PeriodoDeAbertura.cs, SME.Pedagogico.Gestao.WebApp/Controllers/FiltrosController.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaAutoralController.cs, scripts/V30__TIPO_BIMESTRE_SEMESTRE_PERIODO_ABERTURAS.sql
[AB#85297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85297)
=> 85297 - Tratamento para peridiocidade em períodos de abertura

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/linha-aluno/index.js
[AB#86485](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86485)
=> fix 86485 Matemática autoral - ajusta ao selecionar uma resposta

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/linha-aluno/styles.js
[AB#86631](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86631)
=> Nova tabela matemática autoral - Ajuste radio button quando zoom está menos de 100%

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js
[AB#86759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86759)
=> release fix 86759 - Matemática autoral - limpar dados ao trocar de turma e não salvar dados

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js
[AB#86805](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86805)
=> fix 86805 - Matemática - Limpar respostas ao trocar de turma

SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs
[AB#86809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86809)
=> Fix/86809 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs
[AB#86809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86809)
=> fix/86809 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#85360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85360)
=> hom story 85360 - add Semestre para IAD 2023 - Relatórios

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#85360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85360)
=> hom story 85360 - regra para o campo semestre - IAD 2023 - Relatórios

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#88557](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88557)
=> fix/88557 -> master

SME.Pedagogico.Gestao.Aplicacao/Queries/ComponentesCurriculares/ObterCCPorTurmaUsuario/ObterCCPorTurmaUsuarioQueryHandler.cs
[AB#89653](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89653)
=> fix/89653 -> master

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs
[AB#88652](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88652)
=> Fix/88652 -> r2

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportFilter.js
[AB#90094](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90094)
=> 90094 - Ajuste períodos portugues

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs
[AB#88652](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88652)
=> fix/88652 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/index.js
[AB#89544](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89544)
=> r2 fix/89544

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
[AB#90174](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90174)
=> fix/90174 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
[AB#90174](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90174)
=> fix/90174 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/index.js
[AB#89544](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89544)
=> fix/89544 -> master

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#90556](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90556)
=> Fix/90556 -> r2

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#90556](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90556)
=> fix/90556 -> master

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js
[AB#90649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90649)
=> fix/90649 -> r2

SME.Pedagogico.Gestao.Data/Business/SondagemAutoralBusiness.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/aluno.js
[AB#90649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90649)
=> fix/90649 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/funcoes/componentRenderReport.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/PollReport.js
[AB#91443](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91443)
=> master - 91443

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
Fix/92408 -  Erro 500 no relatório IAD por turma
[AB#92408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92408)
=> Fix/92408 -  Erro 500 no relatório IAD por turma

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortugueseCard.js, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesController.cs
[AB#91764](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91764)
=> Sondagem - Alteração de Perguntas Escrita

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#92253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92253)
=> Correção Total Sem Preenchimento

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#93338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93338)
=> 93338 - Valores da tela não tem com os valores do excel

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortuguese3ANivelHipotese.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortugueseCard.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PoolSelectEscritaNivelHipotese.js
=> Incluir níveis como opção de resposta do 3º ano

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/DTO/RelatorioPorTurma/PerguntaPrincipalTurmaProficienciaDTO.cs, SME.Pedagogico.Gestao.Data/Relatorios/Querys/ConsultasRelatorios.cs
[AB#95611](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95611)
=> fix/95611 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLogin/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLoginQueryHandler.cs
[AB#95610](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95610)
=> Fix/95610 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/Usuario/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLogin/ObterPerfisPermissoesTokenDataExpiracaoUsuariosSondagemPorLoginQueryHandler.cs
[AB#95610](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95610)
=> Fix/95610 -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#95111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95111)
=> fix/95111 -> r2

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#95111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95111)
=> fix/95111 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortuguese3ANivelHipotese.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortugueseCard.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PoolSelectEscritaNivelHipotese.js
Retirar para o 3° ano a opção (A - Alfabético) de escrita LP
[AB#98358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98358)
=> Retirar para o 3° ano a opção (A - Alfabético) de escrita LP

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
=> Fix/101555 -> r2

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#101555](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101555)
=> fix/101555 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PoolSelectEscritaNivelHipotese.js
[AB#102057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102057)
=> Fix/102057 -> r2

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/inputs/PoolSelectEscritaNivelHipotese.js
[AB#102057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102057)
=> fix/102057 -> master

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#102979](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102979)
=> fix/102979 -> master

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#103661](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103661)
=> fix/103661 -> master

SME.Pedagogico.Gestao.Data/Business/AlunosBusiness.cs, SME.Pedagogico.Gestao.Data/Integracao/AlunosAPI.cs
[AB#105254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105254)
=> Fix/105254 -> r2

SME.Pedagogico.Gestao.Data/Business/AlunosBusiness.cs, SME.Pedagogico.Gestao.Data/Integracao/AlunosAPI.cs
[AB#105254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105254)
=> fix/105254 -> master

Jenkinsfile, SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs, SME.Pedagogico.Gestao.Infra/Dtos/SGP/UesPorDreSGPDto.cs
[AB#108285](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108285)
=> Fix/108285 -> r2

SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#110264](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110264)
=> fix/110264 -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#112601](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112601)
=> fix/112601 -> master

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortugueseCard.js
[AB#116605](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116605)
=> fix/116605 -> master

SME.Pedagogico.Gestao.Infra/Dtos/Enumerados/GrupoEnum.cs, scripts/V32__ALTERAR_DESCRICAO_GRUPOS.sql
[AB#115079](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115079)
=> 115079 - Renomear os tipos de Sondagem de Lígua Portuguesa

SME.Pedagogico.Gestao.Aplicacao/Queries/Turmas/ObterTurmasPorUeCodigoQueryHandler.cs
[AB#115081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115081)
=> 115081 - Liberar o acesso aos relatórios da Sondagem perfil pap

SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs
[AB#117977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117977)
=> fix/117977 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs
[AB#117977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117977)
=> fix/117977 -> master

SME.Pedagogico.Gestao.Aplicacao/Queries/Periodos/ObterPeriodoFixoAnualPorTipoAnoLetivoEBimestreQuery.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/Periodos/ObterPeriodoFixoAnualPorTipoAnoLetivoEBimestreQueryHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#118188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118188)
=> fix/118188 -> r2

SME.Pedagogico.Gestao.Aplicacao/Queries/Periodos/ObterPeriodoFixoAnualPorTipoAnoLetivoEBimestreQuery.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/Periodos/ObterPeriodoFixoAnualPorTipoAnoLetivoEBimestreQueryHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/UesPorDre/ObterUesPorDreQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/StudentPollPortugueseCard.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/GraficoMatematicaCACM/GraficoMatematicaCACM.js
[AB#118587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118587)
=> r2 - Fix/118587 

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#119282](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119282)
=> Fix/119282 -> r2

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#119286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119286)
=> fix/119286 -> r2

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/RetornoQueryDTO/AlunosNaTurmaDTO.cs
[AB#119663](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119663)
=> fix/119663 -> r2

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs
[AB#119286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119286)
=> fix/119286 -> master

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/RetornoQueryDTO/AlunosNaTurmaDTO.cs
[AB#119663](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119663)
=> fix/119663 -> master

SME.Pedagogico.Gestao.Aplicacao/Queries/Alunos/ObterAlunosAtivosDentroPeriodo/ObterAlunosAtivosDentroPeriodoQuery.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/Alunos/ObterAlunosAtivosDentroPeriodo/ObterAlunosAtivosDentroPeriodoQueryHandler.cs, SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs, SME.Pedagogico.Gestao.Data/Business/SondagemMatematica.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/RetornoQueryDTO/AlunosNaTurmaDTO.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemMatematicaController.cs, SME.Pedagogico.Gestao.WebApp/SME.Pedagogico.Gestao.WebApp.xml
Ajuste na listagem de alunos na digitação de matemática equalizando ao selecionar CA e CM com a listagem mostrada em números coniderando o período selecionado não só a data fim. Equalização da lista de alunos na digitação de matemática em relação a português considerando alunos inativos para verificar se estão dentro do período.
=> Bug: 119494

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/DTO/Portugues/ResultadoAlunoPortuguesDTO.cs, SME.Pedagogico.Gestao.WebApp/Controllers/SondagemPortuguesIntegracaoController.cs, SME.Pedagogico.Gestao.WebApp/Filtros/FiltroIntegracaoExterna.cs, SME.Pedagogico.Gestao.WebApp/Middlewares/ChaveIntegracaoSondagemApi.cs, SME.Pedagogico.Gestao.WebApp/Startup.cs
[AB#120061](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120061)
=> 120061 Criação de Endpoint de Integração do Sondagem

scripts/V33__ADICIONAR_OPCAO_SEM_PREENCHIMENTO.sql
[AB#120271](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120271)
=> Criar script para adicionar a reposta sem preenchimento

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#120256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120256)
[AB#120254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120254)
=>  Tratar relatórios língua portuguesa/matemática "antigo"

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs, SME.Pedagogico.Gestao.Data/DTO/Portugues/Relatorio/RelatorioPortuguesFiltroDto.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/NovaSondagemMatematicaAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/PollFilter.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/checkbox.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/classRecord/SondagemPortuguesAutoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/NovaSondagem/novaSondagemCACM.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/polls/component/SondagemClassSelected.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/tables/questoes-matematica-autoral/index.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemAutoral.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/sagas/SondagemPortugues.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/service/modal-service.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/store/Poll.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/utils/constants.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/utils/validacoes.js, SME.Pedagogico.Gestao.WebApp/ClientApp/yarn.lock, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs, scripts/V33__ADICIONAR_OPCAO_SEM_PREENCHIMENTO.sql
[AB#119041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119041)
[AB#121254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121254)
=> Obrigar preenchimento de todos os estudantes  - story/119041

scripts/V34__ADICIONAR_ORDEM_RESPOSTA_PORTUGUES.sql
[AB#122004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122004)
=>  Está faltando o campo "sem preenchimento"  para IAD - Leitura em voz alta e IAD - produção de texto do 4 ao 9 ano.

SME.Pedagogico.Gestao.Data/Business/NovaOpcaoRespostaSemPreenchimento.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
=> Centralizar regra de nova opção de resposta sem preenchimento

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
=> Correção filtro por todas Dre e todas ue

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
=> Exibir Gráfico

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/DTO/PollReportItemDTO.cs, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js, SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/funcoes/montarPlanilha.js
[AB#122266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122266)
[AB#122301](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122301)
=> Correção Perguntas sem respostas

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#122468](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122468)
=> 122468 - Não apresentado o item sem preenchimento

SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaAutoral.cs, SME.Pedagogico.Gestao.Data/Business/RelatorioMatematicaPorTurmaProficiencia.cs, SME.Pedagogico.Gestao.Data/Integracao/DTO/RetornoQueryDTO/AlunosNaTurmaDTO.cs, SME.Pedagogico.Gestao.WebApp/Controllers/RelatorioSondagemController.cs
[AB#122472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122472)
=> 122472 - Divergência de alunos digitação e relatório

SME.Pedagogico.Gestao.Data/Business/RelatorioPortugues.cs
[AB#122600](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122600)
=> 122600 - total de alunos incorreto.

SME.Pedagogico.Gestao.Data/Business/RelatorioPortuguesCapacidadeLeitura.cs
[AB#122626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122626)
=> 122626 - O campo sem preenchimento para 2023 duplicado.

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs
Ajuste na obtenção do alunos para o bimestre selecionado que ainda não possui período definido.
=> Bug: 122680

SME.Pedagogico.Gestao.Aplicacao/Queries/SondagemAutoral/ObterListagemAutoralQueryHandler.cs
Complemento do ajuste, incluindo a condição para considerar o tipo de período semestral para matrmática à partir do 4º ano.
=> Bug: 122585

SME.Pedagogico.Gestao.Data/Business/PollPortugues.cs
[AB#122997](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122997)
=> 122997 - Ajuste perc total relatorio escrita e leitura

SME.Pedagogico.Gestao.WebApp/ClientApp/src/components/reports/PollReportPortugueseGrid.js
Ajuste no componente de grid do relatório de português aplicando o tratamento de propriedade undefined.
=> Bug: 123049
